### ISSUE TITLE
transitionProperty with multiple values doesn't produce valid CSS

### ISSUE THREAD

**Issue by gatzjames** [johanholmerin/style9#29]
Currently the `transitionProperty` doesn't work when providing an array of properties.
e.g.
```js
let styles = style9.create({
  default: {
    transitionProperty: ["backgroundColor", "color"]
  }
});
```
the resulting class will end up with this css:

```css
.random-name {
  transition-property: backgroundColor color;
}
```
where it should be a comma separated hyphen-case string:

```css
.random-name {
  transition-property: background-color, color;
}
```

For now a workaround would be to provide the values as a string:
```js
let styles = style9.create({
  default: {
    transitionProperty: "backgroundColor, color"
  }
});
```
